### ISSUE TITLE
How do you add authentication to protect the api. 

### ISSUE THREAD

**Issue by phprad** [AlexisTM/Simple-Json-PHP#1]
If you can also also add oauth1 or oauth2 authentication to protect the api, that will also simplify the Json api process.  Thanks for the great library.

**Comment by AlexisTM** [comment]
Hi there,

I can add something like this. Yet, you should be aware of what is oauth. It is not sufficient to "have" oauth to be secure or to prove authenticity.

https://oauth.net/articles/authentication/

Could you share the repetitive code that could be wrapped?

**Comment by phprad** [comment]
Point well noted. Am just trying to know the best mechanism to protect a Json api. So how about JWT. Since session is not best approach in securing an api. 
Thanks

**Comment by AlexisTM** [comment]
Please, tell me exactly what you would like to see and what you are struggling with. 

JWT is the same idea as oauth. It all depends on what you want to achieve.

**Comment by AlexisTM** [comment]
Inactive.
