### ISSUE TITLE
Autoload, not working !!

### ISSUE THREAD

**Issue by DamienW-dev** [AlexisTM/Simple-Json-PHP#2]
Hello, 

The autoloader to composer, doesn't work anymore with your packages.

In my test project, I use two packages:
 - Whoops, which loads properly with the autoloader.
 - Simple\json, which doesn't work :(  

Here is my code is my error:
![Whoops! There was an error  et 8 pages de plus - Personnel - Microsoft Edge](https://user-images.githubusercontent.com/17130917/85614277-0592b000-b65b-11ea-8e1d-b7cc71fdebeb.png)

thanks for your help.
ps: sorry for my bad english

**Comment by AlexisTM** [comment]
I will take a look, do you have an idea of the reason?

**Comment by AlexisTM** [comment]
Could you share your composer.json file?

**Comment by AlexisTM** [comment]
I bumped the version and fixed the deprecated PSR-0 to PSR-4

test.php

```php
<?php
    use Simple\json;
    require('./vendor/autoload.php');
    $json = new json();

    // Ojects to send (fetched from the DB for example)
    $object = new stdClass();
    $object->LastLog = '123456789123456';
    $object->Password = 'Mypassword';
    $object->Dramatic = 'Cat';
    $object->Things = array(1,2,3);

    // Forge the JSON
    $json->data = $object;
    $json->user = "AlexisTM";
    $json->status = 'online';

    // Send the JSON
    $json->send_callback('myAwesomeFunction');
?>
```

Doing the following:

```
php composer.phar require alexistm/simple-json-php:5.1.0
php test.php
```

**Comment by AlexisTM** [comment]
Thanks for pinging, the library needed an update.

I will close this, reopen if it persists.

**Comment by DamienW-dev** [comment]
thank you, for your help.
